### ISSUE TITLE
Chair blocks can't generate with vanilla structures [SERVER SIDE CRASH]

### ISSUE THREAD

**Issue by Blunder-G** [crispytwig/Another-Furniture-Mod#21]
I'm trying to overhoul vanilla and moded strcutures with moded blocks like Another Furniture and Supplementaries. Everytime i try to include Another Furniture's Chairs in Vanilla's structures, it crashes (Only vanilla structures crash, moded ones are okey with chairs]

Here is the crash report:
[crash-2022-08-25_01.20.50-server.txt](https://github.com/starfish-studios/AnotherFurniture/files/9419822/crash-2022-08-25_01.20.50-server.txt)
 
Here is the log:
[latest.log](https://github.com/starfish-studios/AnotherFurniture/files/9419824/latest.log)

**Comment by Synthestra** [comment]
Will be fixed in next update
