### ISSUE TITLE
Error: Failed to read block texture

### ISSUE THREAD

**Issue by ejm554** [crispytwig/Another-Furniture-Mod#25]
When I start my modpack containing AnotherFurniture, I see the following lines in the log, along with subsequent messages that I cannot decipher. Any idea why I'm seeing this and what I can do to resolve it?

```
[18:31:26] [Render thread/ERROR] [ne.me.ev.WoodGood/]: Failed to read block texture at: (another_furniture:block/planter_box/oak, null)
java.io.FileNotFoundException: another_furniture:textures/block/planter_box/oak.png
	at net.minecraft.server.packs.resources.FallbackResourceManager. [...]
```

Link to the full log is [here](https://paste.ee/p/dBHoj).

**Comment by Synthestra** [comment]
Everycompat isn't updating their 1.18.2 versions. Either remove Everycompat or try downgrading Another Furniture to 1.1.3

**Comment by Synthestra** [comment]
Turns out they might be updating it for 1.18.2, stay tuned

**Comment by Synthestra** [comment]
Everycompat 1.18.2 was Updated
