### ISSUE TITLE
Mod causes rendering issues for certain blocks i.e. melons / moss blocks 

### ISSUE THREAD

**Issue by ConqAra** [crispytwig/Another-Furniture-Mod#28]
Maybe some incompatibility with the rendering mods I'm using?
Latest Version for Fabric, 1.19.2
![image](https://user-images.githubusercontent.com/76233356/197318887-495f4bbc-fdda-4dc5-bec2-7eabaf859a70.png)

log: [https://paste.ee/p/qt6p8](https://paste.ee/p/qt6p8)

**Comment by Synthestra** [comment]
Another Furniture doesn't modify any rendering code at all. Have you tried without AF installed?

**Comment by ConqAra** [comment]
I don't know then, because when I remove it there are no rendering issues whatsoever.
