### ISSUE TITLE
Rendering issue with Create 

### ISSUE THREAD

**Issue by Aerioos** [crispytwig/Another-Furniture-Mod#29]
This issue was only present on a Multiplayer Forge server running 40.1.86. 

There were FREQUENT rendering issues with block updates that would only resolve themselves when unloading and reloading the chunks, for example here with the Create mod's belts. I first suspected it was Optifine causing this, uninstalling that and swapping to Rubidium didn't fix it. Uninstalling Rubidium and trying vanilla did not work either. 

Going into Singleplayer did not provide these same issues here.  I then did some quick googling and found this thread regarding [Supplementaries and Create and "unknown mods" causing these same issues. ](https://www.curseforge.com/minecraft/mc-mods/supplementaries/issues/93) The thread ends with a random post recommending you remove Adorn; while I do not have that, I did have AnotherFurniture installed.  Lo and behold removing it did resolve my rendering issues. 

I have quite a few other furniture mods installed as well without issue so I'm quite surprised this one was the one causing it. Unfortunate right now though, considering the quality differential in this mod compared to others. 

![image](https://user-images.githubusercontent.com/54180288/205511139-10ee5124-c3e9-4c23-b37c-ffd895df61b8.png)

**Comment by Synthestra** [comment]
100% sure this isnt an afm issue

**Comment by Synthestra** [comment]
also post your modlist

**Comment by Synthestra** [comment]
@Aerioos

**Comment by Aerioos** [comment]
Apologies for the late reply! I can confirm that the issue was resolved when deleting AFM, readding it created the same issue. 

Modlist is [here ](https://pastebin.com/0fDTX7js)

Running on Forge 40.1.86.

**Comment by crispytwig** [comment]
> Author

AnotherFurniture wasn't included in this modlist. It may have helped to see what version you were on.

Please post a latest.log recreating this issue when you can, and I'll bump this to Synth when he's available.

**Comment by Synthestra** [comment]
I'd say try removing all mods one by one that do optimization tweaks. I'm very sure it's one of those, likely tweaking the atlas or something to that degree
