### ISSUE TITLE
[Mipmap Issue] Dropping Miplevel from 4 to 2 - Fabric 1.19.2

### ISSUE THREAD

**Issue by xR4YM0ND** [crispytwig/Another-Furniture-Mod#36]
`[Worker-Main-9/WARN]: Texture another_furniture:block/table/dark_oak_supports with size 4x4 limits mip level from 4 to 2`

[latest.log](https://gist.github.com/SpigotDE/9af6fb0777811be2a27c41be09a2f4b0)
Line 965

**Comment by xR4YM0ND** [comment]
Any updates on this?

**Comment by xR4YM0ND** [comment]
You still there? 
Sadly we have to use another mod cause of that

**Comment by Synthestra** [comment]
A fix is already done for the next update.

Besides, even as it is currently, all you'll get is a warning in the log. It's not even an error. There should be no visual issues.
