### ISSUE TITLE
[Enhancement] Sofas can act as Seats for Create mod

### ISSUE THREAD

**Issue by pastellexists** [crispytwig/Another-Furniture-Mod#39]
In Create, seats can be assembled as part of a train or other contraption, and can still be interacted with and sat upon even as the train/contraption is in motion. It'd be useful for train design if sofas could assume this functionality, also.

**Comment by Synthestra** [comment]
@pastellexists https://cdn.discordapp.com/attachments/1049377215978143856/1109502467596636251/2023-05-20_14-07-40.mp4

**Comment by pastellexists** [comment]
Looks slick! Thanks so much for your work on this!!
