### ISSUE TITLE
PlanterBox  startup crash with the new 1.20.1 port

### ISSUE THREAD

**Issue by TheWitherlord** [crispytwig/Another-Furniture-Mod#50]
This crash happens with the latest version of everycompat and another furniture.

Versions of Mods:
EveryCompat 1.20-2.6.8
MoonlightLib 1.20-2.8.51
Another_Furniture-forge-1.20.1-3.0.0

If I need to I will open a report for EveryCompat's github

https://gist.github.com/TheWitherlord/24856cd18c3c6d4090d707407ab77043

After new update:
https://gist.github.com/TheWitherlord/cd691e33e3aa05220c4856c718a3d783

**Comment by TheWitherlord** [comment]
https://github.com/MehVahdJukaar/WoodGood/issues/291

**Comment by TheWitherlord** [comment]
https://gist.github.com/TheWitherlord/cd691e33e3aa05220c4856c718a3d783

**Comment by Synthestra** [comment]
everycompat side issue
