### ISSUE TITLE
AnotherFurniture breaks the mineable/axe tag 

### ISSUE THREAD

**Issue by satisfyu** [crispytwig/Another-Furniture-Mod#51]
Hey hey 

currently using [Another Furniture 3.0.0 (Fabric 1.20.1)] which seems to break the mineable/axe tag. 

Couldn't load tag minecraft:mineable/axe as it is missing following references: another_furniture:lamp_connector (from fabric)

**Comment by eefernal** [comment]
Happening on forge version as well.

**Comment by Synthestra** [comment]
fixed in 3.0.1 version

**Comment by satisfyu** [comment]
love <3
