### ISSUE TITLE
False positive Trojan by Bitdefender

### ISSUE THREAD

**Issue by Secretcodrin** [crispytwig/Another-Furniture-Mod#58]
Today Bitdefender chose that the 1.19.2, for forge, version 2.1.2, which was downloaded long ago from curse forge.

I just want to make sure this is the case of a false positive.

I used virus total and there was not even a single trigger on it both uploaded and linked.

**Comment by Synthestra** [comment]
It's definitely a false positive. If you're worried, you can download the source 1.19.2 branch and build it yourself, though it is the 2.1.4 version

**Comment by Secretcodrin** [comment]
Thank you for confirming it! :)
